name: CI & CD

on:
  # 1. Tests auf jedem Branch-Push
  push:
    branches: [ '**' ]
  # und auch bei Pull Requests gegen main
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build with Maven & Run Tests
        run: mvn clean verify --batch-mode

      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-reports-${{ github.ref_name }}
          path: target/surefire-reports/

  deploy:
    name: Deploy JAR on main
    needs: build-and-test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build JAR
        run: mvn clean package --batch-mode

      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v3
        with:
          name: tictactoe-jar
          path: target/*.jar
