name: CI & CD
permissions:
  contents: write
on:
  workflow_dispatch:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven & Run Tests
        run: mvn clean verify --batch-mode

      - name: Sanitize branch name for artifact
        run: |
          # ersetzt alle "/" durch "-"
          echo "SANITIZED_REF=$(echo ${GITHUB_REF_NAME} | sed 's|/|-|g')" >> $GITHUB_ENV

      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v4    # <-- updated to v4
        with:
          name: test-reports-${{ env.SANITIZED_REF }}
          path: target/surefire-reports/

  deploy:
    name: Deploy JAR on main
    needs: build-and-test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build JAR
        run: mvn clean package --batch-mode

      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v4    # <-- updated to v4
        with:
          name: tictactoe-jar
          path: target/*.jar
          
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.${{ github.run_number }}
          release_name: Release v1.0.${{ github.run_number }}
          draft: false
          prerelease: false

      #  JAR in den Release als Asset hochladen
      - name: Upload JAR to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: target/SLT-SS25-TicTacToe_GroupC-1.0-SNAPSHOT.jar
          asset_name: TicTacToe-v1.0.${{ github.run_number }}.jar
          asset_content_type: application/java-archive
